# Generated by Django 3.1 on 2020-08-29 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='branch',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='service.branch'),
        ),
    ]
